### ISSUE TITLE
Push containing multiple commits shows first message

### ISSUE THREAD

**Issue by StefanKoopman** [mschilling/codeheroes-service#5]
Multiple commits in one push show message of first commit instead of last

**Comment by wwolters** [comment]
https://github.com/mschilling/codeheroes-service/blob/develop/functions/github.js#L24
Inserting reverse() here should resolve this.

**Comment by wwolters** [comment]
The same problem is occurring again

**Comment by mschilling** [comment]
Bug fixed in commit bd44520 ..

Now building promises (in sequence) array using reduce for list of commits in same push.

**Comment by mschilling** [comment]
@StefanKoopman @wwolters please re-open if the problem occurs again ;-)
